### PR TITLE
date + time

### PR DESCRIPTION
**Pull request by dmontaner**
At the moment the Rlabkey package reads date/time variables as Date. Hence, the time part is lost. See issue: 
https://www.labkey.org/issues/home/Developer/issues/details.view?issueId=24231

Date/time variables are now read in to R in POSIXct format if they have a __time__ part different form 00-00-00. If there is no time part, or it is 00-00-00 for all rows, then the data are read as Date variables into R.

My modification should work fine provided that the date/time format in the JSON file returned by the web services is in format `Y/m/d H:M:S` or simply `Y/m/d`.  If I understand this is the default or standard in LabKey. Any other format such as for instance `Y-m-d H:M:S` may yield NA values, `null` or any other unformatted value will also be read as NA.

Please confirm that the `Y/m/d H:M:S` format is always used in the web services.

### CODE REVIEW

**Comment by cnathe** [comment]
I checked in a slightly modified version of this change to the develop branch to take into account legacy date formats supplied by the LabKey DateUtil.getJsonDateTimeFormatString() method:
https://github.com/LabKey/labkey-api-r/commit/2d7f48f69d2e7c808000fb5471d94e0d38602c48

As this pull request, the behavior now should be that the date is first parsed using as.POSIXct but then if all time parts are 00:00:00 we revert back to as.Date. 

Thank you for the submitted changes.

**Comment by cnathe** [comment]
Also note that the updated Rlabkey package has not yet been submitted to CRAN. I usually wait a day or two to give our TeamCity automated tests a chance to run with the updated version before submitting.

**Comment by dmontaner** [comment]
Great!!!

You did not include the `tz = "UTC"` option in the `as.POSIXct` call. 

I did find out this to be useful when converting date-time to __just__ date into R. If not used the conversion depends on user configuration and time zone and sometimes the conversion is confusing. 

With my configuration for instance `as.POSIXct` reads date-time values as "BST" and when converted to date times around midnight may go to the day before or after...  

I am not sure how you want the usability of the package to be but be careful with that.

**Comment by dmontaner** [comment]
I think

    d <- as.Date(d, tz = attr (d, which = "tzone"))

will be the more general way to go

**Pull request closed without merging**
