### PR TITLE
Issue 39262: Add support for using username/password authentication via labkey.setDefaults

### PR DESCRIPTION
**Pull request by cnathe**

### CODE REVIEW

**Comment by cnathe** [comment]
[Rlabkey_2.3.4.tar.gz](https://github.com/LabKey/labkey-api-r/files/4140013/Rlabkey_2.3.4.tar.gz)

@labkey-klum @labkey-tchad Hey Karl and Trey, I have these changes for the Rlabkey package that I have tested locally on my Mac with the attached tar.gz. However, this was built with R version 3.6.1 and I believe that TeamCity wants a version built with R 3.5.2 (does that sounds right Trey?). Do either of you know where I can access a Windows machine to setup for Rlabkey package building so that I can generate the correct tar.gz and .zip files?

**Comment by labkey-tchad** [comment]
I do not. However, now that the vignette and docs are gone, it might be possible to have TeamCity build them without having to install a bunch of MiKTeX stuff.

**Comment by cnathe** [comment]
@labkey-tchad Thanks Trey. I have my Windows machine back up and running so I can create the Rlabkey package versions from that again. Trey, can you confirm which version of R I should use so that TeamCity is happy? Is it R 3.5.2?

**Comment by labkey-tchad** [comment]
Confirmed. TeamCity agents are running R 3.5.2

**Review by labkey-klum — APPROVED** [review]
I think it makes sense to change the parameter order setDefaults, although this might break some existing code if they are assuming the previous order. Does it make sense to put something in the release notes to call this out, I don't know if there is a good way to issue a warning either.

**Comment by cnathe** [comment]
> I think it makes sense to change the parameter order setDefaults, although this might break some existing code if they are assuming the previous order. Does it make sense to put something in the release notes to call this out, I don't know if there is a good way to issue a warning either.

@labkey-klum  Good point, Karl. I wasn't thinking about that when changing the param order. I will just put it back to the order it was so that we are backwards compatible. Thanks.

**Pull request merged**
